const dummyMovieData = [
  {
    id: 1,
    movie_name: "The Matrix",
    genre: "Sci-Fi",
    imdb_rating: 8.7,
    release_year: 1999,
    director: "The Wachowskis",
    sequel: true,
  },
  {
    id: 2,
    movie_name: "Pulp Fiction",
    genre: "Crime",
    imdb_rating: 8.9,
    release_year: 1994,
    director: "Quentin Tarantino",
    sequel: false,
  },
  {
    id: 3,
    movie_name: "Forrest Gump",
    genre: "Drama",
    imdb_rating: 8.8,
    release_year: 1994,
    director: "Robert Zemeckis",
    sequel: false,
  },
  {
    id: 4,
    movie_name: "The Dark Knight",
    genre: "Action",
    imdb_rating: 9.0,
    release_year: 2008,
    director: "Christopher Nolan",
    sequel: true,
  },
  {
    id: 5,
    movie_name: "Interstellar",
    genre: "Sci-Fi",
    imdb_rating: 8.6,
    release_year: 2014,
    director: "Christopher Nolan",
    sequel: false,
  },
  {
    id: 6,
    movie_name: "Jurassic Park",
    genre: "Adventure",
    imdb_rating: 8.1,
    release_year: 1993,
    director: "Steven Spielberg",
    sequel: true,
  },
  {
    id: 7,
    movie_name: "The Shawshank Redemption",
    genre: "Drama",
    imdb_rating: 9.3,
    release_year: 1994,
    director: "Frank Darabont",
    sequel: false,
  },
  {
    id: 8,
    movie_name: "Inception",
    genre: "Sci-Fi",
    imdb_rating: 8.8,
    release_year: 2010,
    director: "Christopher Nolan",
    sequel: false,
  },
  {
    id: 9,
    movie_name: "The Godfather",
    genre: "Crime",
    imdb_rating: 9.2,
    release_year: 1972,
    director: "Francis Ford Coppola",
    sequel: true,
  },
  {
    id: 10,
    movie_name: "The Lion King",
    genre: "Animation",
    imdb_rating: 8.5,
    release_year: 1994,
    director: "Roger Allers, Rob Minkoff",
    sequel: true,
  },
  {
    id: 11,
    movie_name: "Titanic",
    genre: "Drama",
    imdb_rating: 7.8,
    release_year: 1997,
    director: "James Cameron",
    sequel: false,
  },
  {
    id: 12,
    movie_name: "Fight Club",
    genre: "Drama",
    imdb_rating: 8.8,
    release_year: 1999,
    director: "David Fincher",
    sequel: false,
  },
  {
    id: 13,
    movie_name: "Avatar",
    genre: "Action",
    imdb_rating: 7.8,
    release_year: 2009,
    director: "James Cameron",
    sequel: true,
  },
  {
    id: 14,
    movie_name: "Forrest Gump",
    genre: "Drama",
    imdb_rating: 8.8,
    release_year: 1994,
    director: "Robert Zemeckis",
    sequel: false,
  },
  {
    id: 15,
    movie_name: "The Lord of the Rings: The Fellowship of the Ring",
    genre: "Adventure",
    imdb_rating: 8.8,
    release_year: 2001,
    director: "Peter Jackson",
    sequel: true,
  },
  {
    id: 16,
    movie_name: "The Lord of the Rings: The Two Towers",
    genre: "Adventure",
    imdb_rating: 8.7,
    release_year: 2002,
    director: "Peter Jackson",
    sequel: true,
  },
  {
    id: 17,
    movie_name: "The Lord of the Rings: The Return of the King",
    genre: "Adventure",
    imdb_rating: 8.9,
    release_year: 2003,
    director: "Peter Jackson",
    sequel: true,
  },
  {
    id: 18,
    movie_name: "Inglourious Basterds",
    genre: "Adventure",
    imdb_rating: 8.3,
    release_year: 2009,
    director: "Quentin Tarantino",
    sequel: false,
  },
  {
    id: 19,
    movie_name: "The Godfather: Part II",
    genre: "Crime",
    imdb_rating: 9.0,
    release_year: 1974,
    director: "Francis Ford Coppola",
    sequel: true,
  },
  {
    id: 20,
    movie_name: "The Godfather: Part III",
    genre: "Crime",
    imdb_rating: 7.6,
    release_year: 1990,
    director: "Francis Ford Coppola",
    sequel: true,
  },
];

module.exports = dummyMovieData;
